fix: remove p2p host 0.0.0.0 from prysm.yaml
lukso-network/network-configs pull request #112
Opened 2023-05-21 13:57 UTC by Hugoo

> --p2p-host-ip value: The IP address advertised by libp2p. This may be used to advertise an external IP.

https://docs.prylabs.network/docs/prysm-usage/parameters

The value 0.0.0.0 is not correct.
Clients should set their own

2023-06-19 11:58 UTC, mxmar commented
@Hugoo I think `devnet` change is missing here

2023-06-20 10:43 UTC, mxmar requested changes
This change is OK, but:
a) CLI needs to attach proper `p2p-host-ip` flag based on end-user IPv4 **public static** address
b) You need to update `devnet` config too (`devnet 7420` directory)
c) @Wolmin needs tu updated https://github.com/lukso-network/network-configs/blob/main/testnet/lighthouse/lighthouse.toml regarding https://app.clickup.com/t/863gevaza?comment=90050018505820 comments

2023-06-21 13:10 UTC, mxmar commented
> 

b) solved :heavy_check_mark:

2023-07-04 14:38 UTC, fhildeb commented
The draft can be closed. We've implemented automated IP fetches for CLI. For custom setups, this needs to be adjusted manually anyways.

2023-09-19 14:49 UTC, Hugoo commented
Thanks @mxmar 

@fhildeb this repo is not linked to the CLI. This setup here is wrong, so let's remove it.

It is up to client runner to add it how they want. But this repo should not put 0.0.0.0 by default.

2023-09-19 16:39 UTC, Hugoo commented
Just tested on the CLI.

It works correctly. 

- If user selects `Y` for the IP, the flag is set correctly.
- If not, the flag is not set. (Atm, it will remain set as 0.0.0.0 which is not good)

2023-09-19 20:55 UTC, merged

2023-09-19 20:57 UTC, Hugoo commented
Sorry, the merge was accidental. Reverted here: https://github.com/lukso-network/network-configs/pull/126