Docker composer and necessary scripts for running lighthouse
lukso-network/network-configs pull request #38
Opened 2022-05-27 07:43 UTC by atif-konasl

Prepared docker compose file with necessary scripts. 
Need to incorporate `lighthouse-docker-test` directory into current directory structure.

2022-05-27 08:01 UTC, NandoTheessen requested changes

2022-05-27 08:13 UTC, atif-konasl commented on l16beta/lighthouse-docker-test/.env
> +PRYSM_BEACON_VERSION="v0.2.2-dev"
Thanks. Changing it.

2022-05-27 08:13 UTC, atif-konasl commented on l16beta/docker/docker-compose.lighthouse.yml
> +    depends_on:
Thanks. Changing it.

2022-05-27 08:17 UTC, atif-konasl commented on l16beta/lighthouse-docker-test/scripts/create-wallet.sh
> +#! /bin/bash
I have tried without scripts but i could not manage to do it.
Help is appreciated

2022-05-27 08:19 UTC, atif-konasl commented on l16beta/docker/docker-compose.lighthouse.yml
> +      --beacon.metrics-addr=http://localhost:5054/metrics
Actually `docker-compose.lighthouse.yml` file was accidentally pushed.
I have already removed that file.

2022-05-27 08:21 UTC, atif-konasl commented on l16beta/docker/docker-compose.lighthouse.yml
> +    container_name: lighthouse_validator
Actually `docker-compose.lighthouse.yml` file was accidentally pushed.
I have already removed that file.

2022-08-01 07:50 UTC, atif-konasl commented
Closing this draft PR

2022-08-01 07:50 UTC, closed without merging