Add lighthouse docker-compose
lukso-network/network-configs pull request #66
Opened 2022-08-01 07:01 UTC by atif-konasl

- Added lighthouse docker-compose file with configs.
- Added `lh-config.yml` file. So when we integrate lh in `lukso-cli`, we need to consider `lh-config.yml` as `config.yml`.
- Added scripts folder for running beacon node, creating lighthouse wallet and running validator client.

2022-08-01 07:09 UTC, NandoTheessen requested changes

2022-08-01 08:27 UTC, atif-konasl commented on l16/scripts/start_validator.sh
> +	  --datadir ./validator_data \
Thanks for pointing this 👍 . Now it looks fine.

2022-08-01 11:05 UTC, eduardxyz approved these changes

2022-08-16 21:00 UTC, NandoTheessen approved these changes

2022-08-17 07:20 UTC, merged